/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EIOSICLOUD_AUTODEFS_H
#define S3EIOSICLOUD_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSICLOUD_NAME "s3eIOSiCloud"
#define S3E_EXT_IOSICLOUD_HASH 0x47c24b3b

#endif /* !S3EIOSICLOUD_AUTODEFS_H */
